# Generated by Django 4.2.1 on 2023-06-08 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_ordersworks_id_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.typework')),
            ],
        ),
        migrations.RemoveField(
            model_name='ordersworks',
            name='id_orders',
        ),
        migrations.RemoveField(
            model_name='ordersworks',
            name='id_works',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='OrdersWorks',
        ),
    ]
