# Generated by Django 4.2.1 on 2023-06-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_rename_ordersworks_orderworks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderWorks',
            new_name='OrderWork',
        ),
    ]
