# Generated by Django 4.2.1 on 2023-06-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_rename_orders_order_rename_orderworks_orderwork'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
        migrations.RenameModel(
            old_name='OrderWork',
            new_name='OrderWorks',
        ),
    ]
