# Generated by Django 4.2.1 on 2023-06-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alter_typework_cost_alter_typework_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typework',
            name='price',
        ),
        migrations.AlterField(
            model_name='typework',
            name='hours',
            field=models.IntegerField(verbose_name='Трудозатраты'),
        ),
    ]
