# Generated by Django 4.2.1 on 2023-06-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_orders_ordersworks_delete_userchoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdersWorks',
            new_name='OrderWorks',
        ),
        migrations.RenameField(
            model_name='orderworks',
            old_name='id_orders',
            new_name='id_order',
        ),
        migrations.RenameField(
            model_name='orderworks',
            old_name='id_works',
            new_name='id_work',
        ),
    ]
