# Generated by Django 4.2.1 on 2023-06-10 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_rename_orders_order_rename_orderworks_orderwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='typework',
            name='price',
            field=models.IntegerField(default=3000, verbose_name='Стоимость нормо-часа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id пользователя'),
        ),
        migrations.AlterField(
            model_name='orderwork',
            name='id_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.order', verbose_name='id заказа'),
        ),
        migrations.AlterField(
            model_name='orderwork',
            name='id_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.typework', verbose_name='id работы'),
        ),
        migrations.AlterField(
            model_name='typework',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='typework',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='typework',
            name='hours',
            field=models.IntegerField(default=1, verbose_name='Трудозатраты в час'),
        ),
        migrations.AlterField(
            model_name='typework',
            name='name_work',
            field=models.CharField(max_length=100, verbose_name='Название работы'),
        ),
        migrations.AlterField(
            model_name='typework',
            name='name_work_estimate',
            field=models.CharField(max_length=100, verbose_name='Название сметной работы'),
        ),
    ]
