# Generated by Django 4.2.1 on 2023-06-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_orderwork_id_order_alter_orderwork_id_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_view',
            field=models.CharField(default='checkbox', max_length=100, verbose_name='Тип категории'),
        ),
        migrations.AlterField(
            model_name='typework',
            name='cost',
            field=models.IntegerField(default=100, verbose_name='Стоимость нормо-часа'),
        ),
        migrations.AlterField(
            model_name='typework',
            name='hours',
            field=models.IntegerField(verbose_name='Трудозатраты'),
        ),
        migrations.AlterField(
            model_name='typework',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Итоговая стоимость'),
        ),
    ]
