# Generated by Django 4.2.1 on 2023-06-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_alter_category_category_view_alter_typework_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typework',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='typework',
            name='hours',
            field=models.IntegerField(default=1, verbose_name='Трудозатраты'),
        ),
        migrations.AlterField(
            model_name='typework',
            name='price',
            field=models.IntegerField(default=3000, verbose_name='Стоимость нормо-часа'),
        ),
    ]
