# Generated by Django 4.2.1 on 2023-06-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_remove_typework_price_alter_typework_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='typework',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='Стоимость нормо-часа'),
        ),
    ]
